### ISSUE TITLE
error in fatrat while backdoor app 

### ISSUE THREAD

**Issue by jacobrohit** [arthurzam/ebuilds#1]
/ ______ \
         || _  _ ||
         ||| || |||          AAAAAA   PPPPPPP   KKK  KKK
         |||_||_|||         AAA  AAA  PPP  PPP  KKK KKK
         || _  _o|| (o)     AAA  AAA  PPP  PPP  KKKKKK
         ||| || |||         AAAAAAAA  PPPPPPPP  KKK KKK
         |||_||_|||         AAA  AAA  PPP       KKK  KKK
         ||______||         AAA  AAA  PPP       KKK  KKK
        /__________\
________|__________|__________________________________________
       /____________\
       |____________|            Dana James Traversie

[*] Running backdoor-apk.sh v0.2.4a on Tue 10 Dec 2019 09:24:46 AM IST
[+] Android manifest permission options:
1) Keep original
2) Merge with payload and shuffle
[?] Please select an Android manifest permission option: 2
[*] Decompiling original APK file...done.
[*] Locating smali file to hook in original project...done.
[+] Package where RAT smali files will be injected: com/cdroid/dominoes
[+] Smali file to hook RAT payload: com/cdroid/dominoes/DominoContext.smali
[*] Generating RAT APK file...done.
[*] Decompiling RAT APK file...done.
[*] Merging permissions of original and payload projects...done.
[*] Injecting helpful Java classes in RAT APK file...done.
[*] Creating new directory in original package for RAT smali files...done.
[+] Inject package path: com/cdroid/dominoes/vdulu
[+] Generated new smali class name for MainBroadcastReceiver.smali: Sehyt
[+] Generated new smali class name for MainService.smali: Gotyt
[+] Generated new smali class name for Payload.smali: Xbhxd
[+] Generated new smali class name for StringObfuscator.smali: Wxuit
[+] Generated new smali method name for StringObfuscator.obfuscate method: vjchy
[+] Generated new smali method name for StringObfuscator.unobfuscate method: ysgxs
[*] Copying RAT smali files to new directories in original project...done.
[*] Fixing RAT smali files...done.
[*] Obfuscating const-string values in RAT smali files...done.
[*] Adding hook in original smali file...done.
[*] Adding persistence hook in original project...done.
[*] Recompiling original project with backdoor...done.
**date: invalid date ‘Sat Sep 26 20:51:24 2511’**
[*] Generating RSA key for signing...done.
[*] Signing recompiled APK...done.
[*] Verifying signed artifacts...done.
[*] Aligning recompiled APK...done.
**[!] Failed to align recompiled APK**

**Comment by arthurzam** [comment]
What does it have meaning with the repository?
